#!/bin/bash

set -eu

if [ $# -gt 1 ]; then
  echo "usage: $0 [run_id]"
fi
if [ $# -eq 1 ]; then
  export RUN_ID="$1"
fi

cd "${BASH_SOURCE[0]%/*}"
source ./inc.harness.sh

export TOTAL_REQUESTS=100000
export REQUESTS_PER_SEC=4000
export CONCURRENCY=4

for sh in ./report-*.sh ; do
  if [ -x "${sh}" ]; then
    "$sh"
  fi
done

# Combine all of the individual reports into an array.
jq -s '.' ./reports/"${RUN_ID}"-*.json \
  > "./reports/${RUN_ID}.json"

## TODO: Move report generation/merging into another tool.

# if [ ! -f ./reports/report.json ]; then
#   cp "./reports/${RUN_ID}.json" ./reports/report.json
# else
#   # Strip the baseline metrics from thec current report in order to use the new baseline.
#   jq 'map(select(.Labels | contains("baseline") | not))' reports/report.json >./reports/old.json
#   # Combine the new reports with the old reports.
#   jq -s 'add' "./reports/${RUN_ID}.json" ./reports/old.json  > ./reports/report.json
# fi

