#!/bin/bash

set -eu

if [ $# -gt 1 ]; then
  echo "usage: $0 [run_id]" >&2
  exit 64
fi
if [ $# -eq 1 ]; then
  export RUN_ID="$1"
fi

cd "${BASH_SOURCE[0]%/*}"
source ./inc.harness.sh

export TOTAL_REQUESTS=100000
export REQUESTS_PER_SEC=4000
export CONCURRENCY=4

if [ "$RUN_ID" = "baseline" ]; then
  ./report-baseline.sh

else
  for sh in ./report-*.sh ; do
    if [[ "$sh" != "./report-baseline.sh" && -x "${sh}" ]]; then
      echo "#; ${sh}"
      "$sh"
    fi
  done
fi

# Combine all of the individual reports into an array.
jq -s '.' "$REPORTS_DIR/$RUN_ID/"*.json \
  > "$REPORTS_DIR/$RUN_ID.json"
