#!/bin/bash

set -eu

if [ $# -gt 1 ]; then
  echo "usage: $0 [run_id]" >&2
  exit 64
fi
if [ $# -eq 1 ]; then
  export RUN_ID="$1"
fi

cd "${BASH_SOURCE[0]%/*}"
source ./inc.harness.sh

export TOTAL_REQUESTS="${TOTAL_REQUESTS:-100000}"
export REQUESTS_PER_SEC="${REQUESTS_PER_SEC:-10000}"
export SERVER_CPUS="${SERVER_CPUS:-1}"
export CLIENT_CPUS="${CLIENT_CPUS:-1}"
export PROXY_CPUS="${PROXY_CPUS:-1}"
export CONCURRENCIES="${CONCURRENCIES:-010 100}"

for CONCURRENCY in $CONCURRENCIES ; do
  export CONCURRENCY
  if [ "$RUN_ID" = "baseline" ]; then
    ./high-concurrency-baseline.sh
  else
    ./high-concurrency-h1.sh
    ./high-concurrency-h2.sh
  fi
done

# Combine all of the individual reports into an array.
jq -s '.' "$REPORTS_DIR/$RUN_ID/"*.json \
    > "$REPORTS_DIR/$RUN_ID.json"
