#!/bin/sh

set -eu

ex_usage() {
  echo "usage: $0 old-reports.json new-reports.json" >&2
  exit 64
}

if [ $# -gt 2 ]; then
    ex_usage
fi

old_reports="$1"
new_reports="$2"

# Strip the baseline metrics from thec current report in order to use the new baseline.
jq 'map(select(.Labels | contains("baseline") | not))' "$old_reports" \
    | jq -s 'add' "$new_reports" - # Combine the new reports with the old reports.


